FROM node:18 AS frontend-builder
WORKDIR /frontend
COPY websocketapp/package.json websocketapp/package=lock.json ./
RUN npm install
COPY websocketapp/ ./
RUN npm run build --configuration=production

FROM nginx:stable
COPY --from=frontend-builder /frontend/dist/websocketapp/browser /usr/share/nginx/html
COPY  nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx","-g","daemon off;"]